#!/usr/bin/env python

import os
import subprocess
import sys

# Required third-party imports, must be specified in pyproject.toml.
import packaging.version
import setuptools
from setuptools.command.build_py import build_py


def process_options():
    """
    Create the options with
    'rootdir', 'short_version', 'version' and 'release' entries.

    Read from the VERSION file to discover the version.  This should be a
    single line file containing valid Python package public identifier (see PEP
    440), for example
      4.5.2rc2
      5.0.0
      5.1.1a1
    We do that here rather than in pyproject.toml so we can apply the local
    versioning number as well.
    """
    rootdir = os.path.dirname(os.path.abspath(__file__))
    version_filename = os.path.join(rootdir, 'VERSION')
    with open(version_filename, "r") as version_file:
        version_string = version_file.read().strip()

    version = packaging.version.parse(version_string)
    short_version = str(version.public)
    release = not version.is_devrelease
    diff = subprocess.run(["git", "diff", "master"], capture_output=True)
    if not release and len(diff.stdout) != 0:
        # Put the version string into canonical form, if it wasn't already.
        version_string = str(version) + "+"
        try:
            git_out = subprocess.run(
                ('git', 'rev-parse', '--verify', '--short=7', 'HEAD'),
                check=True,
                stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            )
            git_hash = git_out.stdout.decode(sys.stdout.encoding).strip()
            version_string += git_hash or "nogit"
        # CalledProcessError is for if the git command fails for internal
        # reasons (e.g. we're not in a git repository), OSError is for if
        # something goes wrong when trying to run git (e.g. it's not installed,
        # or a permission error).
        except (subprocess.CalledProcessError, OSError):
            version_string += "nogit"

    return {
        'rootdir': rootdir,
        'short_version': short_version,
        'version': version_string,
        'release': release,
    }


def create_version_py_file(options):
    """
    Generate and write out the file version.py, which is used to produce the
    '__version__' information for the module.  This function will overwrite an
    existing file at that location.
    """
    filename = os.path.join(
        options['rootdir'], 'src', 'qutip_jax', 'version.py',
    )
    content = "\n".join([
        "# This file is automatically generated during package setup.",
        f"short_version = '{options['short_version']}'",
        f"version = '{options['version']}'",
        f"release = {options['release']}",
    ])
    with open(filename, 'w') as file:
        file.write(content)


class CustomBuildPy(build_py):
    """Custom build_py to generate version.py before packaging."""
    def run(self):
        options = process_options()
        create_version_py_file(options)
        super().run()


if __name__ == "__main__":
    options = process_options()
    setuptools.setup(
        version=options['version'],
        cmdclass={'build_py': CustomBuildPy},
    )
